services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - adminer
    environment:
      NGINX_HOST: ${NGINX_HOST}
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html:ro

  static:
    build: ./requirements/bonus/static
    image: static
    container_name: static
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: unless-stopped
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
      FTP_HOST: ${NGINX_HOST}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
